# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Build takeltest pip package'
  task prod: %w[rubylint
              test
              package:make
              git:tag
              package:upload]
end
