# frozen_string_literal: true

require 'rake'

cmd_make = 'make'

cmd_make_upload = 'make upload'

namespace :package do
  desc 'Make python package'
  task :make do
    @commandss << cmd_make
  end

  desc 'Make python package'
  task :upload do
    @commandss << cmd_make_upload
  end
end
