# frozen_string_literal: true

require 'rake'

cmd_test_unit = 'cd test/unit && ' \
  'pytest'

cmd_test_system_anarchism_project_default = 'cd ' \
  'test/system/anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_anarchism_project_bitboard = 'cd ' \
  'test/system/anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name bitboard'

cmd_test_system_anarchism_role_takel_anarchism_default = 'cd ' \
  'test/system/anarchism/roles/takel-anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_ruby_project_default = 'cd ' \
  'test/system/ruby && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_ruby_project_blocklist_one = 'cd ' \
  'test/system/ruby && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name blocklist_one'

cmd_test_system_ruby_project_blocklist_two = 'cd ' \
  'test/system/ruby && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name blocklist_two'

cmd_test_system_ruby_role_curl_default = 'cd ' \
  'test/system/ruby/roles/curl && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_ruby_role_gpg_default = 'cd ' \
  'test/system/ruby/roles/gpg && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_ruby_project_include = 'cd ' \
  'test/system/ruby && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name include'

cmd_test_system_ruby_role_procps_default = 'cd ' \
  'test/system/ruby/roles/procps && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_ruby_role_vim_default = 'cd ' \
  'test/system/ruby/roles/vim && ' \
  'pytest --cache-clear && ' \
  'molecule test'

desc 'Run tests'
task test: %w[test:unit
              test:system:anarchism:project_default
              test:system:anarchism:project_bitboard
              test:system:anarchism:role_default
              test:system:ruby:default
              test:system:ruby:blocklist_one
              test:system:ruby:blocklist_two
              test:system:ruby:include
              test:system:ruby:role_defaults]

# rubocop:disable Metrics/BlockLength
namespace :test do
  desc 'Run unit tests'
  task :unit do
    @commands << cmd_test_unit
  end
  namespace :system do
    namespace :anarchism do
      desc 'Run system tests anarchism project default'
      task :project_default do
        @commands << cmd_test_system_anarchism_project_default
      end

      desc 'Run system tests anarchism project bitboard'
      task :project_bitboard do
        @commands << cmd_test_system_anarchism_project_bitboard
      end

      desc 'Run system tests anarchism role default'
      task :role_default do
        @commands << cmd_test_system_anarchism_role_takel_anarchism_default
      end
    end

    namespace :ruby do
      desc 'Run system tests ruby project default'
      task :default do
        @commands << cmd_test_system_ruby_project_default
      end

      desc 'Run system tests ruby project blocklist one'
      task :blocklist_one do
        @commands << cmd_test_system_ruby_project_blocklist_one
      end

      desc 'Run system tests ruby project blocklist two'
      task :blocklist_two do
        @commands << cmd_test_system_ruby_project_blocklist_two
      end

      desc 'Run system tests ruby project include'
      task :include do
        @commands << cmd_test_system_ruby_project_include
      end

      desc 'Run system tests ruby role defaults'
      task :role_defaults do
        @commands << cmd_test_system_ruby_role_curl_default
        @commands << cmd_test_system_ruby_role_gpg_default
        @commands << cmd_test_system_ruby_role_procps_default
        @commands << cmd_test_system_ruby_role_vim_default
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
