# frozen_string_literal: true

require 'rake'

cmd_test_unit = 'cd test/unit && ' \
  'pytest'

cmd_test_system_anarchism_project_default = 'cd ' \
  'test/system/anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_anarchism_project_bitboard_provisioner = 'cd ' \
  'test/system/anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name bitboard_provisioner'

cmd_test_system_anarchism_project_bitboard_verifier = 'cd ' \
  'test/system/anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name bitboard_verifier'

cmd_test_system_anarchism_role_takel_anarchism_default = 'cd ' \
  'test/system/anarchism/roles/takel-anarchism && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_env_project_default = 'cd ' \
  'test/system/env && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_env_project_blocklist_one = 'cd ' \
  'test/system/env && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name blocklist_one'

cmd_test_system_env_project_blocklist_two = 'cd ' \
  'test/system/env && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name blocklist_two'

cmd_test_system_env_role_curl_default = 'cd ' \
  'test/system/env/roles/curl && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_env_role_gpg_default = 'cd ' \
  'test/system/env/roles/gpg && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_env_project_include = 'cd ' \
  'test/system/env && ' \
  'pytest --cache-clear && ' \
  'molecule test --scenario-name include'

cmd_test_system_env_role_procps_default = 'cd ' \
  'test/system/env/roles/procps && ' \
  'pytest --cache-clear && ' \
  'molecule test'

cmd_test_system_env_role_vim_default = 'cd ' \
  'test/system/env/roles/vim && ' \
  'pytest --cache-clear && ' \
  'molecule test'

desc 'Run tests'
task test: %w[test:unit
              test:system:anarchism:project_default
              test:system:anarchism:project_bitboard_provisioner
              test:system:anarchism:project_bitboard_verifier
              test:system:anarchism:role_default
              test:system:env:default
              test:system:env:blocklist_one
              test:system:env:blocklist_two
              test:system:env:include
              test:system:env:role_defaults]

# rubocop:disable Metrics/BlockLength
namespace :test do
  desc 'Run unit tests'
  task :unit do
    @commands << cmd_test_unit
  end
  namespace :system do
    namespace :anarchism do
      desc 'Run system tests anarchism project default'
      task :project_default do
        @commands << cmd_test_system_anarchism_project_default
      end

      desc 'Run system tests anarchism project bitboard provisioner'
      task :project_bitboard_provisioner do
        @commands << cmd_test_system_anarchism_project_bitboard_provisioner
      end

      desc 'Run system tests anarchism project bitboard verifier'
      task :project_bitboard_verifier do
        @commands << cmd_test_system_anarchism_project_bitboard_verifier
      end

      desc 'Run system tests anarchism role default'
      task :role_default do
        @commands << cmd_test_system_anarchism_role_takel_anarchism_default
      end
    end

    namespace :env do
      desc 'Run system tests env project default'
      task :default do
        @commands << cmd_test_system_env_project_default
      end

      desc 'Run system tests env project blocklist one'
      task :blocklist_one do
        @commands << cmd_test_system_env_project_blocklist_one
      end

      desc 'Run system tests env project blocklist two'
      task :blocklist_two do
        @commands << cmd_test_system_env_project_blocklist_two
      end

      desc 'Run system tests env project include'
      task :include do
        @commands << cmd_test_system_env_project_include
      end

      desc 'Run system tests env role defaults'
      task :role_defaults do
        @commands << cmd_test_system_env_role_curl_default
        @commands << cmd_test_system_env_role_gpg_default
        @commands << cmd_test_system_env_role_procps_default
        @commands << cmd_test_system_env_role_vim_default
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
