# frozen_string_literal: true

require 'rake'

cmd_test_unit = 'cd test/unit && ' \
  'pytest'

cmd_test_system_anarchism_project_default = 'cd ' \
  'test/system/anarchism && ' \
  'molecule test'

cmd_test_system_anarchism_project_takelbuild_provisioner = 'cd ' \
  'test/system/anarchism && ' \
  'molecule test --scenario-name takelbuild_provisioner'

cmd_test_system_anarchism_project_takelbuild_verifier = 'cd ' \
  'test/system/anarchism && ' \
  'molecule test --scenario-name takelbuild_verifier'

cmd_test_system_anarchism_role_takel_anarchism_default = 'cd ' \
  'test/system/anarchism/roles/takel-anarchism && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

cmd_test_system_env_project_default = 'cd ' \
  'test/system/env && ' \
  'molecule test'

cmd_test_system_env_project_blocklist_one = 'cd ' \
  'test/system/env && ' \
  'molecule test --scenario-name blocklist_one'

cmd_test_system_env_project_blocklist_two = 'cd ' \
  'test/system/env && ' \
  'molecule test --scenario-name blocklist_two'

cmd_test_system_env_role_curl_default = 'cd ' \
  'test/system/env/roles/curl && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

cmd_test_system_env_role_gpg_default = 'cd ' \
  'test/system/env/roles/gpg && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

cmd_test_system_env_project_include = 'cd ' \
  'test/system/env && ' \
  'molecule test --scenario-name include'

cmd_test_system_env_role_procps_default = 'cd ' \
  'test/system/env/roles/procps && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

cmd_test_system_env_role_vim_default = 'cd ' \
  'test/system/env/roles/vim && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

cmd_test_system_multi_default = 'cd ' \
  'test/system/multi && ' \
  'molecule test'

cmd_test_system_sidecar_molecule_role_default = 'cd ' \
  'test/system/sidecar/molecule/playbooks/roles/my_sidecar_role && ' \
  'ANSIBLE_ROLES_PATH=../ molecule test'

desc 'Run tests'
task test: %w[
  test:unit
  test:system:anarchism:project_default
  test:system:anarchism:project_takelbuild_provisioner
  test:system:anarchism:project_takelbuild_verifier
  test:system:anarchism:role_default
  test:system:env:default
  test:system:env:blocklist_one
  test:system:env:blocklist_two
  test:system:env:include
  test:system:env:role_defaults
  test:system:multi:default
  test:system:sidecar:default
]

# rubocop:disable Metrics/BlockLength
namespace :test do
  desc 'Run unit tests'
  task :unit do
    @commands << cmd_test_unit
  end
  namespace :system do
    namespace :anarchism do
      desc 'Run system tests anarchism project default'
      task :project_default do
        @commands << cmd_test_system_anarchism_project_default
      end

      desc 'Run system tests anarchism project takelbuild provisioner'
      task :project_takelbuild_provisioner do
        @commands << cmd_test_system_anarchism_project_takelbuild_provisioner
      end

      desc 'Run system tests anarchism project takelbuild verifier'
      task :project_takelbuild_verifier do
        @commands << cmd_test_system_anarchism_project_takelbuild_verifier
      end

      desc 'Run system tests anarchism role default'
      task :role_default do
        @commands << cmd_test_system_anarchism_role_takel_anarchism_default
      end
    end

    namespace :env do
      desc 'Run system tests env project default'
      task :default do
        @commands << cmd_test_system_env_project_default
      end

      desc 'Run system tests env project blocklist one'
      task :blocklist_one do
        @commands << cmd_test_system_env_project_blocklist_one
      end

      desc 'Run system tests env project blocklist two'
      task :blocklist_two do
        @commands << cmd_test_system_env_project_blocklist_two
      end

      desc 'Run system tests env project include'
      task :include do
        @commands << cmd_test_system_env_project_include
      end

      desc 'Run system tests env role defaults'
      task :role_defaults do
        @commands << cmd_test_system_env_role_curl_default
        @commands << cmd_test_system_env_role_gpg_default
        @commands << cmd_test_system_env_role_procps_default
        @commands << cmd_test_system_env_role_vim_default
      end
    end

    namespace :multi do
      desc 'Run system tests multi'
      task :default do
        @commands << cmd_test_system_multi_default
      end
    end

    namespace :sidecar do
      desc 'Run system tests molecule sidecar'
      task :default do
        @commands << cmd_test_system_sidecar_molecule_role_default
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
