name: takeltest

on:
  push:
  workflow_dispatch:

jobs:
  takeltest:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create pypi config file
        run: echo -e "[pypi]\nusername = __token__\npassword = ${{ secrets.PIP_PASSWORD }}" > .pypirc

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Install tau
        run: gem install takeltau

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          echo "docker_tag: latest-amd64" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Read mutagen version
        run: |
          MUTAGEN=$(docker inspect --format '{{ index .Config.Labels "mutagen" }}' takelwerk/takelbuild:latest-amd64)
          echo "MUTAGEN=$MUTAGEN" >> "$GITHUB_ENV"

      - name: Install mutagen
        run: |
          MUTAGEN_FILE=https://github.com/mutagen-io/mutagen/releases/download/v${{ env.MUTAGEN }}/mutagen_linux_amd64_v${{ env.MUTAGEN }}.tar.gz
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O /tmp/mutagen.tar.gz $MUTAGEN_FILE
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin
          mutagen daemon start

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Move pypi config file
        run: tau docker container command "mv /project/.pypirc $HOME"

      - name: Install dev version of takeltest
        run: |
          tau docker container command "sudo pip3 uninstall --yes takeltest"
          tau docker container command "sudo pip3 install /project"

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Run tests
        run: tau docker container command "ANSIBLE_ROLES_PATH=../../ rake test"

      - name: Reset ownership
        run: sudo chown -R $USER $(pwd)

      - name: Build pip package
        run: tau docker container command "rake package:make"

      - name: Upload pip package
        run: tau docker container command "rake package:upload"
